app1/urls.py
from django.urls import path
from app1.views import *
app_name='something'
urlpatterns=[
    path('chennai/',chennai,name='chennai'),
    path('delhi/',delhi,name='delhi'),
]

project13/urls.py
from django.contrib import admin
from django.urls import path,include
import app1
from app2.views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',kerala,name='kerala'),
    path('app2/',tirupati,name='tirupati'),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render
def chennai(request):
    return render(request,'chennai.html')

# Create your views here.
def delhi(request):
    return render(request,'delhi.html')

app2/views.py
from django.shortcuts import render
def kerala(request):
    return render(request,'kerala.html')

# Create your views here.
def tirupati(request):
    return render(request,'tirupati.html')

templates/chennai.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1 style="color:blueviolet">This is chennai html page</h1>
        <a href="{% url 'something:delhi' %}">go to delhi page</a>
        <a href="{% url 'kerala' %}">go to kerala page</a>
        <a href="{% url 'tirupati' %}">go to tirupati page</a>
        <h1 style="color:brown">Chennai is most famous cities in our country</h1>
    </center>
    
</body>
</html>

templates/delhi.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1 style="color:purple">This is delhi html page</h1>
    <a href="{% url 'something:chennai' %}">go to chennai page</a>
    <a href="{% url 'kerala' %}">go to kerala page</a>
    <a href="{% url 'tirupati' %}">go to tirupati page</a>
    <h1 style="color:orangered">delhi capital domain of india</h1>
    </center>
    
</body>
</html>

templates/kerala.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1 style="color:slateblue">
            This page belongs to kerala html page
        </h1>
        <a href="{% url 'something:chennai' %}">Go to chennai page</a>
        <a href="{% url 'something:delhi' %}">Go to delhi page</a>
        <a href="{% url 'tirupati' %}">Go to tirupati page</a>
        <h1 style="color:pink">kerala is the most beautiful place in our country</h1>
    </center>
</body>
</html>

templates/tirupati.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1 style="color:red">This is tirupati html page</h1>
        <a href="{% url 'something:chennai' %}">Go to chennai page</a>
        <a href="{% url 'something:delhi' %}">Go to delhi page</a>
        <a href="{% url 'kerala' %}">Go to kerala page</a>
        <h1 style="color:blue">This is holiastic place in our country</h1>
    </center>
</body>
</html>